image: cosmwasm/cw-gitpod-base:v0.16

vscode:
  extensions:
    - rust-lang.rust

tasks:
  - name: Dependencies & Build
    init: |
      cargo build
  - name: Setup Environment
    command: source <(curl -sSL https://raw.githubusercontent.com/CosmWasm/testnets/master/oysternet-1/defaults.env)
