# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml

on: [push, pull_request]

name: Basic

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: stable
      RUST_TARGET: wasm32-unknown-unknown
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install ${{ env.RUST_VERSION }} toolchain
        run: |
          rustup install --no-self-update ${{ env.RUST_VERSION }}
          rustup default ${{ env.RUST_VERSION }}
          rustup component add clippy rustfmt rust-src
          rustup target add ${{ env.RUST_TARGET }}
      - name: Run unit tests
        env:
          RUST_BACKTRACE: 1
        run: cargo test --locked
      - name: Compile WASM contract
        env:
          RUSTFLAGS: "-C link-arg=-s"
        run: cargo wasm --locked

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install ${{ env.RUST_VERSION }} toolchain
        run: |
          rustup install --no-self-update ${{ env.RUST_VERSION }}
          rustup default ${{ env.RUST_VERSION }}
          rustup component add clippy rustfmt
          rustup target add ${{ env.RUST_TARGET }}
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --all -- -D warnings
      - name: Generate Schema
        run: cargo schema --locked
      - name: Schema Changes
        # fails if any changes not committed
        run: git diff --exit-code schema
